### ISSUE TITLE
Allow others to define their own `-Bits` derives

### ISSUE THREAD

**Issue by hecatia-elegua** [hecatia-elegua/bilge#11]
We currently [split attributes](https://github.com/hecatia-elegua/bilge/blob/c52793c22b5f7cb5542821e5bb1c2c06c36ec50a/bilge-impl/src/bitsize.rs#L11) into those using field information and those using the generated internal value.
All attributes which are not [handled here](https://github.com/hecatia-elegua/bilge/blob/c52793c22b5f7cb5542821e5bb1c2c06c36ec50a/bilge-impl/src/bitsize.rs#L134) just get applied on the internal value.
To allow devs to define their own bit-derives, we just need to define a convention for them.
We have two ways to do this:
1. a `Bits` postfix in the derive's name

This would clutter the code less and can only lead to breakage if some other unrelated macro uses the same postfix (in which case one could report that macro here so we can handle it differently).

2. let the user do the splitting

```rust
#[derive(Debug, PartialEq, Clone, Copy)]
#[bitsize(2)]
#[derive(TryFromBits)]
enum HaveFun {
    Yes, No, Maybe,
}
```
This would even allow you to use normal derive names below `#[bitsize]` and let them change into our names automatically, i.e. `#[derive(Debug)]` turns into `#[derive(DebugBits)]`, which means users could just remove `#[bitsize]` when rust starts supporting arbitrary ints in the future. Edit: but that's a bit hacky and maybe doesn't let you auto-import.

**Comment by hecatia-elegua** [comment]
I think we should go for (1.) to keep readability.
If anyone wants to contribute, this is a nice little task, feel free to ask for help though!

**Comment by gwendalF** [comment]
@hecatia-elegua Hello, I would like to try implementing this. Just to be sure, you would like to have the possibility of the users of this crate to define their own macro? And be able to write something like this:


```rust
#[derive(bitsize(6))]
#[derive (CustomBits)]
struct Packet {
field1...,
field2....
}
``` 

So CustomBits has still Access to fields of the struct?

**Comment by hecatia-elegua** [comment]
@gwendalF Hey there, thank you.
Yes, exactly.
