### ISSUE TITLE
"associated constant `FILLED` is private" error when using bitsized structs from another file in module

### ISSUE THREAD

**Issue by ktrieu** [hecatia-elegua/bilge#25]
I'm running into an error in the `bitsized` macro if I use a bitsized struct defined in another file.

The full error I'm getting is:
```
error[E0624]: associated constant `FILLED` is private
 --> src\example\first.rs:5:1
  |
5 | #[bitsize(8)]
  | ^^^^^^^^^^^^^ private associated constant
  |
 ::: src\example\second.rs:5:1
  |
5 | #[bitsize(6)]
  | ------------- private associated constant defined here
  |
  = note: this error originates in the attribute macro `bitsize` (in Nightly builds, run with -Z macro-backtrace for more info)
```

You can look [here](https://github.com/ktrieu/bilge-test/) for a full example of what I'm talking about, but the gist of it is:

If I have this in `example/second.rs`:

```
use bilge::prelude::*;

#[bitsize(6)]
#[derive(FromBits)]
pub struct Sibling {
    field: u2,
    other: u4,
}
```

and this in `example/first.rs`:

```
use bilge::prelude::*;

use super::second::Sibling;

#[bitsize(8)]
#[derive(FromBits)]
pub struct Example {
    sibling: Sibling,
    field: u2,
}
```

I get the error attached.

That is, using other bitsized structs as members doesn't seem to work when they're imported from another file in the same module. The error goes away if I include both structs in the same file, like:

```
use bilge::prelude::*;

#[bitsize(6)]
#[derive(FromBits)]
pub struct Sibling {
    field: u2,
    other: u4,
}

#[bitsize(8)]
#[derive(FromBits)]
pub struct Example {
    sibling: Sibling,
    field: u2,
}
```

In case it helps, I ran into this trying to build structs to represent GDT/IDT entries for some OS dev I was doing.

**Comment by hecatia-elegua** [comment]
Thank you for the bug report.
I know how to fix it, will publish a fix asap.
This is actually interesting, since basic tests wouldn't even catch this.
The gist of it is that `Sibling` defines a `const FILLED`, which is used by `Example`, it's just not `pub`.

**Comment by ktrieu** [comment]
I can confirm this works. Thanks for fixing this so fast, and thanks for the library! Aside from this problem, it's been great to use.
