### ISSUE TITLE
Change the return value of `TryFrom`?

### ISSUE THREAD

**Issue by hecatia-elegua** [hecatia-elegua/bilge#49]
As noticed in #40, it's not really useful to return the raw value on error.
Until we have an opinion on this, we should change the error type to something unuseful, so we don't end up breaking a lot more people later (and at some point this crate is supposed to be stable).

As discussed a bit on discord, `struct BitsError;` would be extensible.

One syntax break would still be possible:
```rust
match res {
    Ok(a) => todo!(),
    // people should use Err(_) instead:
    Err(bilge::BitsError) => todo!(),
}
```
~~But I think it's good enough since it's easy to search&replace with `_`.~~
But we can handle this by adding `#[non_exhaustive]` on `BitsError` and having a function which just returns `BitsError`.
(btw. the above code sample says `unit struct BitsError is private`, even though it's just non_exhaustive)

**Comment by pickx** [comment]
since it has to be possible to create the value on the user's side, we can't really do anything fancy. I agree with this solution
