### ISSUE TITLE
`#[derive(Default)` introduces unsoundness in structs

### ISSUE THREAD

**Issue by pickx** [hecatia-elegua/bilge#50]
you can `#[derive(Default)]` on bitsized structs, since `arbitray_int::UInt` is `Default`. this has the same effect as setting the inner value to `0`. this can introduce unsoundness:

```rust
use bilge::prelude::*;

#[bitsize(2)]
#[derive(TryFromBits, Debug)]
enum Unfilled {
    A = 1,
    B = 2,
    C = 3,
}

#[bitsize(2)]
#[derive(TryFromBits, Default, DebugBits)]
struct Unsound {
    field1: Unfilled,
}

fn main () {
    let via_try_from = Unsound::try_from(u2::new(0));
    assert!(via_try_from.is_err());
    
    let via_default = Unsound::default(); // via_default.field1 is now a value of `Unfilled` that is not allowed
    dbg!(via_default); // this crashes at runtime (panicked at 'unreachable')
}
```

**Comment by hecatia-elegua** [comment]
wonderful

**Comment by hecatia-elegua** [comment]
`DefaultBits`? 🙂
Or we can probably just forbid `derive(Default)` or spit out a `const NO: Unsound = Unsound::try_from(u2::new(0)).expect("deriving Default is unsound")`

**Comment by pickx** [comment]
here are the use cases I can think of for`Default::default()` with a `bilge` struct as of today (I apologize if I missed anything)
1. the user has a specific default bit pattern in mind, and has added appropriate `#[default]` attributes for every enum
2. deriving it because the user would like an all-zero bit pattern
3. a user needs a new instance of a complicated type, but does not feel like spelling out every single field for `new()`"
4. deriving it because it's easy to do so, and seems useful/harmless

I argue that cases 3 and 4 might be common, and furthermore that the user might not be aware of the possible implications of deriving `Default`.
in use case 2 (and arguably 3), what the person really wants is an all-zero constructor.

so maybe what we want is to discourage (or even disallow) `derive(Default)` and suggest something like [`zerocopy::FromBytes`](https://docs.rs/zerocopy/latest/zerocopy/trait.FromBytes.html), or the less strict [`bytemuck::Zeroable`](https://docs.rs/zeroable/0.2.0/zeroable/zeroable_docs/index.html) for users who want an all-zero constructor. `Unsound::zeroed()` is more explicit than `Unsound::default()`.

**Comment by hecatia-elegua** [comment]
One thing: if `Filled`, you're allowed to zero, currently.
So, maybe we generate "Default is forbidden" if we see `TryFromBits` + `Default`?
