### ISSUE TITLE
Move `FILLED` to `Bitsized`

### ISSUE THREAD

**Issue by pickx** [hecatia-elegua/bilge#51]
We use `const FILLED` to do a compile-time check for `TryFrom`/`From`, however it is currently codegen'd as an associated const of the type the `#[Bitsized(N)]` attribute is on. So this implementation detail is exposed to the user via IDE autocomplete.

Instead, we can keep this const in the generated `Bitsized` impl, since it is expected that every type which implements `Bitsized` is either codegen'd by `#[Bitsized(N)]` or is `uN`/`bool`.

**Comment by hecatia-elegua** [comment]
```rust
#[bitsize(7)]
struct Struct {
    field1: u2,
    field2: u3,
    field3: Enum,
}
#[bitsize(2)]
#[derive(FromBits)]
enum Enum {
    A, B, C, D
}

impl From<u7> for Struct {
    fn from(value: u7) -> Self {
        check::<u2>();
        check::<u3>();
        check::<Enum>();
        Self { value }
    }
}
fn check<T: Filled>() {}
trait Filled {}
impl<T> Filled for T
where
    T: Bitsized + From<<T as Bitsized>::ArbitraryInt>
{}
```
is this it? can probably be even easier
